config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root to: "meetings#index"
  resources :meetings
  resources :users, only: [:edit, :update]
  resources :rooms, only: [:index ,:new, :create, :destroy] do
    resources :messages, only: [:index, :create]
  end
  
 
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  validates :category, presence: true
  validates :start_time, presence: true
  validates :finish_time, presence: true

  belongs_to :user
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @meetings = Meeting.where(user_id: current_user).page(params[:page]).order(start_time: :asc).per(3)
  end

  def show
  end

  def new
    @meeting = Meeting.new
  end

  def edit
  end

  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_meeting
    @meeting = Meeting.find(params[:id])
  end

  def meeting_params
    params.require(:meeting).permit(:category, :start_time, :finish_time).merge(user_id: current_user.id)
  end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.erb
<%= form_with(model: meeting, local: true) do |form| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
        <% meeting.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :finish_time %>
    <%= form.datetime_select :finish_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>TimeSchedule</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Show', @meeting %> 
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
  
          <% if user_signed_in? %>
           <div align="right"> <%= link_to "ログアウト", destroy_user_session_path, method: :delete,class: :logout_btn  %></div>
           <% if current_page?(meetings_path) || current_page?(root_path)%>
            <%= link_to "チャットルームへ", rooms_path,class: :link_btn %><br><br>
             <%= link_to "新しい予定",  new_meeting_path,class: :link_btn %><br>
             
            <% else %>
          <%= link_to "学習管理へ", meetings_path,class: :study_btn%>
          <% end %>
          <% else%>
          <div class='test'><%= link_to "ログイン", new_user_session_path, class: :link_btn %>
             <%= link_to "新規登録",  new_user_registration_path, class: :link_btn %>
             <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class: :link_btn %>
          <% end%></div><br>

        
      
          
<table>
  <thead>
    <tr><br>
      <th>Category</th>
      <th>Start time</th>
      <th>finish time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meetings.each do |meeting| %>
      <tr>
        <td><%= meeting.category %></td>
        <td><%= meeting.start_time.strftime("%Y-%m-%d %H:%M:%S") %></td><td><%= meeting.finish_time.strftime("%Y-%m-%d %H:%M:%S") %></td>
        <td><%= link_to '詳細', meeting %></td>
        <td><%= link_to '編集', edit_meeting_path(meeting) %></td>
        <td><%= link_to '削除', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
ページ<%= paginate(@meetings) %> 
<br>
<%= month_calendar events: @meetings do |date, meetings| %>
  <%= date.day %>

  <% meetings.each do |meeting| %>
    <div>
      <%= meeting.category %>
    </div>
  <% end %>
<% end %>

app/views/meetings/new.html.erb
<%= render 'form', meeting: @meeting %>
<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @meeting.category %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @meeting.start_time.strftime("%Y-%m-%d %H:%M:%S")%>
  <strong>finish time:</strong>
  <%= @meeting.finish_time.strftime("%Y-%m-%d %H:%M:%S") %>
</p>

<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>